name: Download Wix Website

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  download_site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Playwright
        run: |
          npm install playwright
          npx playwright install  # Install the required browsers

      - name: Download Website with Playwright
        run: |
          node -e "
          const { chromium } = require('playwright');
          const fs = require('fs');
          const path = require('path');
          const url = 'https://elite-team-eight.vercel.app';
          
          (async () => {
            const browser = await chromium.launch();
            const page = await browser.newPage();
            await page.goto(url, { waitUntil: 'networkidle' });
            await page.waitForTimeout(5000); // Wait to ensure all content is loaded

            // Save the HTML content
            const content = await page.content();
            fs.writeFileSync(path.join('website', 'index.html'), content);

            // Take a screenshot for verification
            await page.screenshot({ path: 'website/screenshot.png' });

            await page.close();
            await browser.close();
          })();
          "

      - name: Upload Downloaded Files
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-website
          path: website/
