name: Scrape and Process Website

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch: # Manual trigger

jobs:
  scrape-and-process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests

    - name: Download Website with HTTrack
      run: |
        sudo apt-get install httrack -y
        httrack https://educationwithwork.wixsite.com/index/ -O ./site/ "+*.wixsite.com/*" \
        --quiet --depth=3 --disable-security-limits --robots=0

    - name: Run Python Processing Script
      run: python process.py  # Assuming your script is named process.py and is located in the repo

    - name: Copy Files to Main Directory
      run: python process.py  # process.py will also handle copying to the main directory

    - name: Pull latest changes from GitHub
      run: git pull origin main  # Pull the latest changes before pushing

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Processed and scraped website"
    
    - name: Push changes
      run: |
        git push
