name: Download Wix Website

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  download_site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Playwright
        run: npm install playwright

      - name: Download Website with Playwright
        run: |
          node -e "
          const { chromium } = require('playwright');
          (async () => {
            const browser = await chromium.launch();
            const page = await browser.newPage();
            await page.goto('https://educationwithwork.wixsite.com/index', { waitUntil: 'networkidle' });
            await page.waitForTimeout(5000); // Wait to ensure all content is loaded
            await page.content();  // This retrieves the HTML content
            await page.screenshot({ path: 'website/screenshot.png' }); // Save screenshot for verification
            await page.pdf({ path: 'website/website.pdf', format: 'A4' }); // Save PDF of page
            await page.close();
            await browser.close();
          })();
          "

      - name: Upload Downloaded Files
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-website
          path: website/
