import time
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options

# Set up Chrome options
options = Options()
options.add_argument('--headless')  # Run in headless mode for GitHub Actions
options.add_argument('--no-sandbox')  # Bypass OS security model
options.add_argument('--disable-dev-shm-usage')  # Overcome limited resource problems

# Specify the path to ChromeDriver (this should match where it's installed in GitHub Actions)
service = Service('/usr/local/bin/chromedriver')

# Start the WebDriver and load the page
driver = webdriver.Chrome(service=service, options=options)
driver.get('https://educationwithwork.wixsite.com/index')

# Scroll down to load all dynamic content
last_height = driver.execute_script('return document.body.scrollHeight')

# Loop to scroll until all content is loaded
while True:
    driver.execute_script('window.scrollTo(0, document.body.scrollHeight);')
    time.sleep(2)  # Wait for the page to load
    new_height = driver.execute_script('return document.body.scrollHeight')
    if new_height == last_height:
        break
    last_height = new_height

# Save the loaded page source
with open('site/content.html', 'w', encoding='utf-8') as f:
    f.write(driver.page_source)

# Close the WebDriver
driver.quit()
